### ISSUE TITLE
Adicionar Actions

### ISSUE THREAD

**Issue by renanbastos93** [jeffotoni/gocorreio.rastreio#1]
Estava pensando, podemos adicionar um pipeline para futuras solicitaçoes de recebimento passem para um verificador de lint/format e security. Além disso, para rodar os testes. 
Que tu acha?

**Comment by jeffotoni** [comment]
é uma boa só propor e fazer pull request e sapecamos

**Comment by renanbastos93** [comment]
Beleza, irei fazer mais tarde.

**Comment by renanbastos93** [comment]
Na verdade já foi feito, podemos fechar a issue, certo.
Closed
